name: Check terraform file format

on:
  pull_request:
    branches: [ main ]
jobs: 
  check_format: 
    runs-on: ubuntu-latest 
    name: Check terraform files are formatted or not
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: terraform format 
        uses: dflook/terraform-fmt-check@v1
        id: fmt-check
        with:
         path: ../
      - name: Wrong format
        if: ${{ failure() && steps.fmt-check.outputs.failure-reason == 'check-failed' }}
        run: echo "terraform format check failed"